project:
  type: book
  output-dir: docs
  resources: 
    - "img/" 

book:
  title: "SCCDS Professional Development Handbook"
  reader-mode: true
  author:   
  - name: Isaac Quintanilla Salinas
    url: https://www.inqs.info
    orcid: 0000-0002-1137-4310
  chapters:
    - index.qmd
    - preface.qmd
    - part: r.qmd
      chapters: 
        - rstudio.qmd
        - r_basics.qmd
        - r_plot.qmd
        - r_stats.qmd
        - r_adv.qmd
        - r_base.qmd
        - r_tidyverse.qmd
        - r_teaching.qmd
    - part: python.qmd
      chapters: 
        - python_basics.qmd
        - python_ds.qmd
        - python_teaching.qmd
    - part: statistics.qmd
      chapters: 
        - estimators.qmd
        - bootstrapping.qmd
        - permutations.qmd
        - mc.qmd
    - part: data.qmd
      chapters: 
        - positron.qmd
        - tidytuesday.qmd
    - part: oc.qmd
      chapters: 
        - notebooks.qmd
        - google.qmd
        - jupyterhub.qmd
        - lms.qmd
    - part: reporting.qmd
      chapters:
        - markdown.qmd
        - document.qmd
        - presentations.qmd
    - part: vc.qmd
      chapters: 
        - vc_github.qmd
        - vc_git.qmd
        - website.qmd
  repo-url: https://github.com/inqs909/sccds_pdbook/
  sidebar:
    style: docked
    background: light
  downloads: [pdf, epub]

knitr:
  opts_chunk: 
    echo: true
    eval: true
    message: false
    warnings: false
    comment: "#>" 
    error: true

format:
  html:
    theme: cosmo
    toc: true
    number-depth: 2
    margin-header: |
      ![](/img/SCCDS.png)


execute:
  freeze: auto

editor: source

